
services:
  psychoapp_backend:
    build:
      context: .
      dockerfile: DockerfileBackend
      target: go_backend-runner
    image: psychoapp-backend
    volumes:
      - ./.env:/app/.env:ro
      - ./database.db:/app/database.db
      - ./migrations:/app/migrations:ro
    ports:
      - 8181:8181

  psychoapp_backend_front:
    image: psychoapp-backend-front
    extends:
      service: psychoapp_backend
    depends_on:
      psychoapp_front:
        condition: service_started
    volumes:
      - front-container:/app/front:ro
    environment:
      - FRONTEND_PATH=front

  psychoapp_bot:
    build:
      context: .
      dockerfile: DockerfileBot
      target: go_bot-runner
    image: psychoapp-bot
    volumes:
      - ./.env:/app/.env:ro
      - ./database.db:/app/database.db
      - ./migrations:/app/migrations:ro

  psychoapp_front:
    build:
      context: .
      dockerfile: DockerfileFront
      args:
        - FRONT_BUILD_FOLDER=/app/front
    image: psychoapp-front
    volumes:
      - front-container:/app/front

volumes:
  front-container: