x-args: &args
  APP_FOLDER: /app
  GO_BACKEND_EXE: psychoapp
  GO_BOT_EXE: psychoapp_bot
  FRONT_BUILD_FOLDER: /app/front
  FRONT_LOCAL_FOLDER: psycho-app-admin

services:
  psychoapp_dev:
    build:
      context: .
      dockerfile: DockerfileBackend
      target: go_backend-runner
      args:
        <<: *args
    image: psychoapp-backend-dev
    volumes:
      - ./.env:/app/.env:ro
      - ./database.db:/app/database.db
      - ./migrations:/app/migrations:ro
    ports:
      - 8181:8181

  psychoapp_front_dev:
    image: psychoapp-backend-front-dev
    extends:
      service: psychoapp_dev
    depends_on:
      front_builder:
        condition: service_started
    volumes:
      - front-container:/app/front:ro
    environment:
      - FRONTEND_PATH=front

  psychoapp_bot_dev:
    build:
      context: .
      dockerfile: DockerfileBot
      target: go_bot-runner
      args:
        <<: *args
    image: psychoapp-bot-dev
    volumes:
      - ./.env:/app/.env:ro
      - ./database.db:/app/database.db
      - ./migrations:/app/migrations:ro

  # builder images

  front_builder:
    build:
      context: .
      dockerfile: DockerfileFront
      args:
        <<: *args
    image: psychoapp-front-builder
    volumes:
      - front-container:/app/front

volumes:
  front-container: