CREATE TABLE user
(
    ID    INTEGER PRIMARY KEY AUTOINCREMENT,
    Name  TEXT NOT NULL,
    Email TEXT NOT NULL UNIQUE
);

CREATE TABLE patient
(
    ID    INTEGER PRIMARY KEY AUTOINCREMENT,
    Name  TEXT    NOT NULL,
    Email TEXT    NOT NULL UNIQUE,
    UserId       INTEGER NOT NULL,
    FOREIGN KEY (UserId) REFERENCES user (ID)
);

CREATE TABLE story
(
    ID        INTEGER PRIMARY KEY AUTOINCREMENT,
    Date      DATE    NOT NULL,
    Situation TEXT    NOT NULL,
    Mind      TEXT    NOT NULL,
    Emotion   TEXT    NOT NULL,
    Power     INTEGER NOT NULL,
    PatientId      INTEGER NOT NULL,
    FOREIGN KEY (PatientId) REFERENCES patient (ID)
);